"""
Django settings for ussd_helper project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
"""
Django settings for ussd_helper project.
"""

from pathlib import Path
import os
import sys

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = ['*']

# COMPLETELY DISABLE DATABASE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# Disable all database-related functionality
DATABASE_ROUTERS = []
DEFAULT_AUTO_FIELD = None

# Minimal apps - NO DATABASE APPS
INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'corsheaders',
    'bank_agent',
]

# Minimal middleware - NO DATABASE MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ussd_helper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'ussd_helper.wsgi.application'

# No password validators
AUTH_PASSWORD_VALIDATORS = []

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CORS_ALLOW_ALL_ORIGINS = True

# Monkey-patch to prevent migration commands
def disable_migrations():
    return None

from django.core.management.commands import migrate
original_handle = migrate.Command.handle

def fake_handle(self, *args, **options):
    self.stdout.write("Migrations disabled - no database needed")
    return

migrate.Command.handle = fake_handle

# Production settings
if os.getenv('RAILWAY_STATIC_URL'):
    DEBUG = False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    CSRF_TRUSTED_ORIGINS = ['https://web-production-f7377.up.railway.app']